import 'dotenv/config';
import express from'express';import cors from'cors';import helmet from'helmet';import rateLimit from'express-rate-limit';import multer from'multer';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import XLSX from'xlsx';
import{studentCourse}from'./matching.js';import{initializeDatabase,initializeAdmin,initializeTests,initializeDefaultAssignments,assignDefaultTests,uniqueCode,syncExpired,statusOf,transaction,query,one,many}from'./db.js';
const app=express(),bad=(r,m,s=400)=>r.status(s).json({error:m}),wrap=f=>(q,r,n)=>Promise.resolve(f(q,r,n)).catch(n);
const origins=(process.env.FRONTEND_ORIGIN||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean);
app.use(helmet());app.use(cors({origin:(o,cb)=>!o||!origins.length||origins.includes(o.replace(/\/$/,''))?cb(null,true):cb(Error('CORS manzili ruxsat etilmagan'))}));app.use(express.json({limit:'1mb'}));
const auth=wrap(async(q,r,n)=>{try{const p=jwt.verify(q.headers.authorization?.replace(/^Bearer /,''),process.env.JWT_SECRET),u=await one('SELECT id,role,code,name,group_name AS "group",subject,level FROM users WHERE id=$1',[p.id]);if(!u)return bad(r,'Hisob topilmadi',401);q.user=u;n()}catch{return bad(r,'Qayta tizimga kiring',401)}}),admin=(q,r,n)=>q.user.role==='admin'?n():bad(r,'Ruxsat yo‘q',403);
app.get('/api/health',wrap(async(q,r)=>{await one('SELECT 1');r.json({ok:true,database:'postgresql'})}));
app.post('/api/login',rateLimit({windowMs:900000,limit:20}),wrap(async(q,r)=>{const code=String(q.body.code||'').trim(),role=String(q.body.role||''),u=await one('SELECT * FROM users WHERE code=$1 AND role=$2',[code,role]);if(!['admin','student'].includes(role)||!u||(role==='student'?!/^\d{6}$/.test(code):!bcrypt.compareSync(String(q.body.password||''),u.password_hash)))return bad(r,role==='student'?'Kod noto‘g‘ri':'Login yoki parol noto‘g‘ri',401);r.json({token:jwt.sign({id:u.id},process.env.JWT_SECRET,{expiresIn:'12h'}),user:{id:u.id,role:u.role,name:u.name,code:u.code,level:u.level,subject:u.subject,group:u.group_name}})}));
app.get('/api/me',auth,(q,r)=>r.json(q.user));
app.get('/api/admin/overview',auth,admin,wrap(async(q,r)=>{await syncExpired();const students=(await one("SELECT COUNT(*)::int n FROM users WHERE role='student'")).n,tests=(await one('SELECT COUNT(*)::int n FROM tests')).n,c=await many('SELECT status,COUNT(*)::int n FROM assignments GROUP BY status'),num=s=>c.find(x=>x.status===s)?.n||0,recent=await many('SELECT a.id,a.status,a.score,a.total,a.started_at,a.submitted_at,u.name student,u.code,t.title test FROM assignments a JOIN users u ON u.id=a.student_id JOIN tests t ON t.id=a.test_id ORDER BY COALESCE(a.submitted_at,a.started_at,t.created_at) DESC LIMIT 8');r.json({students,tests,active:num('active'),completed:num('completed'),pending:num('pending'),recent})}));
app.get('/api/admin/students',auth,admin,wrap(async(q,r)=>r.json(await many("SELECT id,code,name,group_name AS \"group\",subject,level,created_at FROM users WHERE role='student' ORDER BY id DESC"))));
async function createStudent(d,c){const name=String(d.name||'').trim(),group=String(d.group||'').trim(),subject=String(d.subject||'').trim(),level=String(d.level||'').trim();if(!name||!group||!subject||!level)throw Error('Ism familiya, guruh, fan va darajani to‘ldiring');if([name,group,subject,level].some(x=>x.length>120))throw Error('Maydon juda uzun');const code=await uniqueCode(c),u=await one("INSERT INTO users(role,code,password_hash,name,group_name,subject,level) VALUES('student',$1,$2,$3,$4,$5,$6) RETURNING id",[code,bcrypt.hashSync(code,10),name,group,subject,level],c);await assignDefaultTests(u.id,c);return{id:u.id,code,name,group,subject,level}}
app.post('/api/admin/students',auth,admin,wrap(async(q,r)=>r.status(201).json(await createStudent(q.body))));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5242880}});
app.post('/api/admin/students/import',auth,admin,upload.single('file'),wrap(async(q,r)=>{if(!q.file||!/\.(xlsx|xls|csv)$/i.test(q.file.originalname))return bad(r,'Excel yoki CSV fayl yuboring');const wb=XLSX.read(q.file.buffer,{type:'buffer'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(rows.length>1000)return bad(r,'Bir martada 1000 tagacha o‘quvchi');const created=[],errors=[];for(let i=0;i<rows.length;i++){const n=Object.fromEntries(Object.entries(rows[i]).map(([k,v])=>[k.toLowerCase().replace(/[\s_’']/g,''),v]));try{created.push(await createStudent({name:n.ismfamilya||n.fio||n.name,group:n.gurux||n.guruh||n.group,subject:n.fan||n.subject,level:n.daraja||n.level}))}catch(e){errors.push({row:i+2,error:e.message})}}r.json({created,errors})}));
app.get('/api/admin/students/template',auth,admin,(q,r)=>{const s=XLSX.utils.json_to_sheet([{'Ism familya':'Aliyev Ali',Gurux:'101-A',Fan:'HTML/CSS',Daraja:'HTML/CSS'}]),b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,s,'Oquvchilar');r.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').set('Content-Disposition','attachment; filename="oquvchilar_namuna.xlsx"').send(XLSX.write(b,{type:'buffer',bookType:'xlsx'}))});
app.patch('/api/admin/students/:id',auth,admin,wrap(async(q,r)=>{const{name,group,subject,level}=q.body;if(!name||!group||!subject||!level)return bad(r,'Barcha maydonlarni to‘ldiring');const x=await query("UPDATE users SET name=$1,group_name=$2,subject=$3,level=$4 WHERE id=$5 AND role='student'",[name,group,subject,level,q.params.id]);if(!x.rowCount)return bad(r,'O‘quvchi topilmadi',404);await assignDefaultTests(Number(q.params.id));r.json({ok:true})}));
app.delete('/api/admin/students/:id',auth,admin,wrap(async(q,r)=>{await query("DELETE FROM users WHERE id=$1 AND role='student'",[q.params.id]);r.json({ok:true})}));
app.get('/api/admin/tests',auth,admin,wrap(async(q,r)=>r.json(await many('SELECT t.*,COUNT(q.id)::int question_count FROM tests t LEFT JOIN questions q ON q.test_id=t.id GROUP BY t.id ORDER BY t.id DESC'))));
app.post('/api/admin/tests',auth,admin,wrap(async(q,r)=>{const{subject='',level='',questions}=q.body,title=String(q.body.title||'').trim();if(!title||!Array.isArray(questions)||!questions.length||questions.length>100)return bad(r,'Test nomi va 1–100 ta savol kiriting');for(const x of questions)if(!x.question||!Array.isArray(x.options)||x.options.length!==4||![0,1,2,3].includes(Number(x.correct)))return bad(r,'Har savolga matn, 4 variant va to‘g‘ri javob kiriting');const id=await transaction(async c=>{const t=await one('INSERT INTO tests(title,subject,level,duration_minutes) VALUES($1,$2,$3,30) RETURNING id',[title,subject,level],c);for(let i=0;i<questions.length;i++){const x=questions[i];await query('INSERT INTO questions(test_id,question,options,correct,position) VALUES($1,$2,$3,$4,$5)',[t.id,x.question,x.options,Number(x.correct),i],c)}return t.id});r.status(201).json({id})}));
app.get('/api/admin/tests/:id',auth,admin,wrap(async(q,r)=>{const t=await one('SELECT * FROM tests WHERE id=$1',[q.params.id]);if(!t)return bad(r,'Test topilmadi',404);r.json({...t,questions:await many('SELECT * FROM questions WHERE test_id=$1 ORDER BY position',[t.id])})}));
app.delete('/api/admin/tests/:id',auth,admin,wrap(async(q,r)=>{await query('DELETE FROM tests WHERE id=$1',[q.params.id]);r.json({ok:true})}));
app.post('/api/admin/assignments',auth,admin,wrap(async(q,r)=>{const test=Number(q.body.testId),ids=q.body.studentIds;if(!await one('SELECT 1 FROM tests WHERE id=$1',[test])||!Array.isArray(ids)||!ids.length)return bad(r,'Test va o‘quvchilarni tanlang');let count=0;for(const id of new Set(ids.map(Number)))count+=(await query("INSERT INTO assignments(student_id,test_id) SELECT id,$2 FROM users WHERE id=$1 AND role='student' ON CONFLICT DO NOTHING",[id,test])).rowCount;r.json({count})}));
app.get('/api/admin/assignments',auth,admin,wrap(async(q,r)=>{await syncExpired();r.json((await many('SELECT a.*,u.name student,u.code,u.group_name AS "group",u.subject,u.level,t.title test,t.duration_minutes FROM assignments a JOIN users u ON u.id=a.student_id JOIN tests t ON t.id=a.test_id ORDER BY a.id DESC')).map(x=>({...x,answers:undefined})))}));
app.get('/api/admin/assignments/:id',auth,admin,wrap(async(q,r)=>{await syncExpired();const a=await one('SELECT a.*,u.name student,u.code,t.title test FROM assignments a JOIN users u ON u.id=a.student_id JOIN tests t ON t.id=a.test_id WHERE a.id=$1',[q.params.id]);if(!a)return bad(r,'Natija topilmadi',404);r.json({...a,questions:await many('SELECT id,question,options,correct FROM questions WHERE test_id=$1 ORDER BY position',[a.test_id])})}));
app.get('/api/student/assignments',auth,wrap(async(q,r)=>{if(q.user.role!=='student')return bad(r,'Ruxsat yo‘q',403);await assignDefaultTests(q.user.id);await syncExpired();r.json(await many("SELECT a.id,a.status,a.started_at,t.title,t.subject,t.level,t.duration_minutes,(SELECT COUNT(*)::int FROM questions z WHERE z.test_id=t.id) question_count FROM assignments a JOIN tests t ON t.id=a.test_id LEFT JOIN seed_registry s ON s.test_id=t.id WHERE a.student_id=$1 AND(s.key IS NULL OR s.key=$2 OR a.status='active') ORDER BY a.id DESC",[q.user.id,studentCourse(q.user)]))}));
async function assignment(q,r){const a=await one('SELECT a.*,t.title,t.subject,t.duration_minutes FROM assignments a JOIN tests t ON t.id=a.test_id WHERE a.id=$1 AND a.student_id=$2',[q.params.id,q.user.id]);if(!a){bad(r,'Test topilmadi',404);return}const s=await one('SELECT key FROM seed_registry WHERE test_id=$1',[a.test_id]);if(s&&s.key!==studentCourse(q.user)&&a.status!=='active'){bad(r,'Bu test darajangizga mos emas',403);return}await statusOf(a);return one('SELECT a.*,t.title,t.subject,t.duration_minutes FROM assignments a JOIN tests t ON t.id=a.test_id WHERE a.id=$1',[a.id])}
app.post('/api/student/assignments/:id/start',auth,wrap(async(q,r)=>{const a=await assignment(q,r);if(!a)return;if(a.status==='completed')return bad(r,'Test topshirilgan',409);if(a.status==='pending')await query("UPDATE assignments SET status='active',started_at=NOW() WHERE id=$1",[a.id]);r.json({ok:true})}));
app.get('/api/student/assignments/:id',auth,wrap(async(q,r)=>{const a=await assignment(q,r);if(!a)return;if(a.status!=='active')return bad(r,'Testni boshlang',409);r.json({id:a.id,title:a.title,subject:a.subject,startedAt:a.started_at,durationMinutes:a.duration_minutes,answers:a.answers||{},questions:await many('SELECT id,question,options FROM questions WHERE test_id=$1 ORDER BY position',[a.test_id])})}));
async function save(a,input,c){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Javoblar noto‘g‘ri');const ok=new Set((await many('SELECT id FROM questions WHERE test_id=$1',[a.test_id],c)).map(x=>String(x.id))),ans={...(a.answers||{})};for(const[id,v]of Object.entries(input)){if(!ok.has(id)||![0,1,2,3].includes(v))throw Error('Javob noto‘g‘ri');ans[id]=v}await query('UPDATE assignments SET answers=$1 WHERE id=$2',[ans,a.id],c)}
app.patch('/api/student/assignments/:id/answers',auth,wrap(async(q,r)=>{const a=await assignment(q,r);if(!a)return;if(a.status!=='active')return bad(r,'Vaqt tugagan yoki test topshirilgan',409);await save(a,q.body.answers);r.json({ok:true})}));
app.post('/api/student/assignments/:id/submit',auth,wrap(async(q,r)=>{const a=await assignment(q,r);if(!a)return;if(a.status!=='active')return bad(r,'Test topshirilgan',409);await transaction(async c=>{if(q.body.answers)await save(a,q.body.answers,c);const ans=(await one('SELECT answers FROM assignments WHERE id=$1 FOR UPDATE',[a.id],c)).answers,qs=await many('SELECT id,correct FROM questions WHERE test_id=$1',[a.test_id],c),score=qs.filter(x=>Object.hasOwn(ans,x.id)&&Number(ans[x.id])===x.correct).length;await query("UPDATE assignments SET status='completed',submitted_at=NOW(),score=$1,total=$2 WHERE id=$3",[score,qs.length,a.id],c)});r.json({ok:true})}));
app.use('/api',(q,r)=>bad(r,'Manzil topilmadi',404));app.use((e,q,r,n)=>{console.error(e);r.status(500).json({error:['Javob noto‘g‘ri','Javoblar noto‘g‘ri'].includes(e.message)?e.message:'Server xatosi'})});
await initializeDatabase();await initializeAdmin();await initializeTests();await initializeDefaultAssignments();const port=Number(process.env.PORT||4000);app.listen(port,'0.0.0.0',()=>console.log(`API ${port}-portda ishladi`));
